Algoritmo "Categoria_do_atleta"
// Autor : António Mota
// Data  : 28/9/2017
// Descrição : Categoria do atleta

Var
idade: inteiro
Inicio
escreva("Escreva a idade maior que 4:")
Leia (idade)
  escolha idade
  caso 5 ate 7
  escreval("Infantil")
  caso 8 ate 10
  escreval("Infantil B")
  caso 11 ate 13
  escreval("Juvenil A")
  caso 14 ate 17
  escreval("Juvenil B")
  caso 18 ate 150
  escreval("Sénior")
  fimescolha


Fimalgoritmo