Algoritmo "Nota_0-20"
// Autor : António Mota
// Data  : 22/9/2017
// Descrição : Nota_0-20

Var
opcao: inteiro
Inicio
escreva("Digite o valor da nota do aluno: ")
Leia (opcao)
  escolha opcao
  caso 0 ate 4
  escreva("Mau")
  caso 5 ate 9
  escreva("Mediocre")
  caso 10 ate 13
  escreva("Suficiente")
  caso 14 ate 17
  escreva("Bom")
  caso 18 ate 20
  escreva("Muito Bom")
  fimescolha


Fimalgoritmo